[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
startCommand = "./Foko.API"
numReplicas = 1
preDeployCommand = ["echo 'No pre-deploy step'"]
port = 8080
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
